export default {
  backgroundConnected: 'backgroundConnected',
  checkContentConnection: 'checkContentConnection',
  contentConnected: 'contentConnected',
  createShipmentFromSelection: 'createShipmentFromSelection',
  foundElementContent: 'foundElementContent',
  getSelectorContent: 'getSelectorContent',
  getStorage: 'getStorage',
  mapField: 'mapField',
  mappedField: 'mappedField',
  popupConnected: 'popupConnected',
  saveMappedField: 'saveMappedField',
  switchedTab: 'switchedTab',
  trackShipment: 'trackShipment',
};
