export default {
  backgroundConnected: 'backgroundConnected',
  checkContentConnection: 'checkContentConnection',
  contentConnected: 'contentConnected',
  createShipment: 'createShipment',
  createShipmentFromSelection: 'createShipmentFromSelection',
  deleteField: 'deleteField',
  foundContent: 'foundContent',
  foundElementContent: 'foundElementContent',
  foundPreset: 'foundPreset',
  foundSelectorsAndContent: 'foundSelectorsAndContent',
  getContent: 'getContent',
  getPreset: 'getPreset',
  // getFieldSettingsForURL: 'getFieldSettingsForURL',
  getStorage: 'getStorage',
  mapField: 'mapField',
  mappedField: 'mappedField',
  newShipment: 'newShipment',
  popupConnected: 'popupConnected',
  saveMappedField: 'saveMappedField',
  stopListening: 'stopListening',
  switchedTab: 'switchedTab',
  trackShipment: 'trackShipment',
};
