export default {
  backgroundConnected: 'backgroundConnected',
  checkContentConnection: 'checkContentConnection',
  contentConnected: 'contentConnected',
  createShipment: 'createShipment',
  createShipmentFromSelection: 'createShipmentFromSelection',
  foundElementContent: 'foundElementContent',
  getElementsContent: 'getElementsContent',
  getStorage: 'getStorage',
  mapField: 'mapField',
  deleteField: 'deleteField',
  mappedField: 'mappedField',
  newShipment: 'newShipment',
  popupConnected: 'popupConnected',
  saveMappedField: 'saveMappedField',
  switchedTab: 'switchedTab',
  trackShipment: 'trackShipment',
};
