name: 'On push ⚙️'

on:
  push:
    branches:
      - alpha
      - beta
      - main

    paths-ignore:
      - ./**/*.md
      - ./.idea/**

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  rebase-prs:
    uses: ./.github/workflows/workflow-call-rebase-prs.yml
    secrets: inherit
