name: 'Publish extensions 🚀'

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        description: 'The target to publish the extensions to'
        default: 'default'
        options:
          - 'default'
          - 'trustedTesters'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        id: build

      - name: 'Publish MyParcel extension'
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist/myparcel.zip
          publish: true
          publish-target: ${{ github.event.inputs.target }}
          extension-id: ${{ vars.EXTENSION_ID_MYPARCEL }}
          client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}

      - name: 'Publish Flespakket extension'
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist/flespakket.zip
          publish: true
          publish-target: ${{ github.event.inputs.target }}
          extension-id: ${{ vars.EXTENSION_ID_FLESPAKKET }}
          client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}

      - name: 'Publish SendMyParcel extension'
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist/sendmyparcel.zip
          publish: true
          publish-target: ${{ github.event.inputs.target }}
          extension-id: ${{ vars.EXTENSION_ID_SENDMYPARCEL }}
          client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}

  rebase-prs:
    needs: release
    uses: ./.github/workflows/workflow-call-rebase-prs.yml
    secrets: inherit
