name: 'Release new version 🚀'

on:
  workflow_dispatch:

  schedule:
    # every day at 18:00 UTC
    - cron: '0 18 * * *'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  #  release:
  #    runs-on: ubuntu-22.04
  #    needs:
  #      - build
  #    steps:
  #      - uses: myparcelnl/actions/setup-git-credentials@v4
  #        id: credentials
  #        with:
  #          app-id: ${{ secrets.MYPARCEL_APP_ID }}
  #          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
  #
  #      - uses: actions/checkout@v4
  #        with:
  #          token: ${{ steps.credentials.outputs.token }}
  #          fetch-depth: 0
  #
  #      - uses: myparcelnl/actions/yarn-install@v4
  #        with:
  #          node-version: ${{ vars.NODE_VERSION }}
  #
  #      - name: 'Download build'
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: build
  #
  #      - name: 'Release'
  #        # language=bash
  #        run: |
  #          npx semantic-release
  #        env:
  #          GITHUB_TOKEN: ${{ steps.credentials.outputs.token }}
  #          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  rebase-prs:
    needs: build
    uses: ./.github/workflows/rebase-prs.yml
    secrets: inherit
